### ISSUE TITLE
[[Feature Reqest]] Temporarily open and edit any file as plain text file via context menu or command.

### ISSUE THREAD

**Issue by nostalgic22** [dbarenholz/obsidian-plaintext#13]
I want to edit my handwritten svg file - or any other file - in ipad without registering extensions. So I can edit a file without risk of destroying other plugin. It’s easy on desktop environment but It’s not on mobile environment especially ipad. So I think it is nice to be able to edit target file as plaintext temporarily.

**Comment by dbarenholz** [comment]
@nostalgic22 So you want to open files which are already registered by Obsidian itself?

For other plugins this is relatively simple, since I forcefully delete their views and deregister them (if the setting is True), but it requires the user to manually disable and re-enable the plugin when they're done. So I cannot use the same logic since then you'd have to close and re-open Obsidian every time you edit an SVG.

Perhaps there's a better way to do this?

**Comment by nostalgic22** [comment]
Well It is unfortunate since it sounds like impossible to impelement smoothly. I hope oneday we can find a solution.
